### ISSUE TITLE
Error 'PUT Failed with: 422'

### ISSUE THREAD

**Issue by bvelazquez1** [techyowl/homebridge-august-smart-locks#38] opened 2021-02-16 16:42 UTC
I recently started encountering this error with my August Lock. The logs are below:

[16/02/2021, 11:36:56] [AugustLocks] [August Front Door] Error 'PUT failed with: 422' setting lock state: lock
[16/02/2021, 11:37:11] [AugustLocks] [August Front Door] Error 'PUT failed with: 422' setting lock state: unlock
[16/02/2021, 11:38:25] [AugustLocks] [August Front Door] Error 'PUT failed with: 422' setting lock state: lock

I can unlock the lock with the August app but it doesn't work in the Apple Home app. I logged out of the plugin in Homebridge and reauthenticated with a new 2FA code.

**Comment by Greminn** [comment] 2021-05-13 00:02
I can confirm the same... Again can lock and unlock with the app (via wifi/bluetooth and when away from home), but not homebridge:

[13/05/2021, 11:42:06 am] [AugustLocks] [August Front Door] Error 'PUT failed with: 560' setting lock state: lock
[13/05/2021, 11:42:23 am] [AugustLocks] [August Front Door] Error 'PUT failed with: 560' setting lock state: lock
[13/05/2021, 11:49:34 am] [AugustLocks] [August Front Door] Error 'PUT failed with: 408' setting lock state: lock

**Comment by techyowl** [comment] 2021-12-01 01:20
closing due to this being dormant.

**Closed by techyowl** 2021-12-01 01:20 UTC
